const Map<String, Map<String, String>> appStrings = {
  'en': {
    'preparingDashboard': 'Preparing your air dashboard...',
    'loadingInsights': 'Loading Bengaluru air insights...',
    'readyToExplore': 'Ready to explore the city air.',
    'appSubtitleNative': 'ವಾಯು ನೇತ್ರ',
    'appTagline': '"The Eye on Bengaluru\'s Air"',
    'welcomeBack': 'Welcome Back',
    'loginToReport': 'Login to report pollution',
    'emailAddress': 'Email address',
    'password': 'Password',
    'login': 'Login',
    'newHere': 'New here?',
    'register': 'Register',
    'createAccount': 'Create Account',
    'joinCommunity': 'Join Bengaluru\'s air quality community',
    'fullName': 'Full Name',
    'passwordMin': 'Password (min 8 chars)',
    'confirmPassword': 'Confirm Password',
    'strongPassword': 'Strong password',
    'useEightChars': 'Use 8+ characters',
    'passwordsDoNotMatch': 'Passwords do not match',
    'livePollutionMap': 'Live Pollution Map',
    'reports': 'reports',
    'report': 'Report',
    'viewFullReport': 'View Full Report',
    'reportPollution': 'Report Pollution',
    'tapToTakePhoto': 'Tap to take photo',
    'orUseButtons': 'or use buttons below',
    'camera': 'Camera',
    'gallery': 'Gallery',
    'nextAddDetails': 'Next: Add Details',
    'areaHint': 'Area (e.g. Koramangala, Whitefield)',
    'useMyGpsLocation': 'Use My GPS Location',
    'detecting': 'Detecting...',
    'descriptionHint': 'Describe the pollution (optional — Nova AI will analyze the photo)',
    'novaDescription': 'Amazon Nova 2 Lite will analyze your photo and generate a KSPCB complaint letter automatically',
    'back': 'Back',
    'analyze': 'Analyze',
    'novaAnalyzing': 'Nova 2 Lite Analyzing...',
    'uploadingPhoto': 'Uploading photo...',
    'analyzingPollution': 'Nova 2 Lite analyzing pollution...',
    'generatingComplaint': 'Generating complaint letter...',
    'healthRisk': 'Health risk',
    'confidence': 'Confidence',
    'recommendations': 'Recommendations',
    'myReports': 'My Reports',
    'reportAgain': 'Report Again',
    'loginToSubmit': 'Login to Submit',
    'photoSavedLogin': 'Your photo is saved. Login to submit.',
    'loginSubmit': 'Login & Submit',
    'aiAgent': 'AI Agent',
    'poweredByNova': 'Powered by Amazon Nova 2 Lite',
    'askAirQuality': 'Ask about Bengaluru\'s air quality',
    'askAboutAir': 'Ask about air quality...',
    'cleanAirAreasToday': 'Clean air areas in Bengaluru today',
    'worstPollutionAreas': 'Worst pollution areas this week',
    'safeForJogging': 'Is Koramangala safe for jogging?',
    'showStats': 'Show Bengaluru pollution stats',
    'howToComplaint': 'How to file a KSPCB complaint?',
    'findCleanAir': 'Find Clean Air',
    'aqiScale': 'AQI SCALE',
    'directions': 'Directions',
    'statistics': 'Statistics',
    'personal': 'Personal',
    'community': 'Community',
    'yourImpact': 'YOUR IMPACT',
    'severityBreakdown': 'SEVERITY BREAKDOWN',
    'bengaluruCommunity': 'BENGALURU COMMUNITY',
    'fullLeaderboard': 'FULL LEADERBOARD',
    'total': 'Total',
    'today': 'Today',
    'areas': 'Areas',
    'critical': 'Critical',
    'points': 'Points',
    'profile': 'Profile',
    'memberSince': 'Member since',
    'badges': 'BADGES',
    'language': 'LANGUAGE',
    'english': 'English',
    'kannada': 'Kannada',
    'hindi': 'Hindi',
    'shareApp': 'Share App',
    'logout': 'Logout',
    'notLoggedIn': 'Not logged in',
    'quickActions': 'QUICK ACTIONS',
    'reportPollutionAction': 'Report Pollution',
    'liveMap': 'Live Map',
    'cleanAir': 'Clean Air',
    'todayInBengaluru': 'TODAY IN BENGALURU',
    'myRecentReports': 'MY RECENT REPORTS',
    'viewAll': 'View All',
    'noReportsYet': 'No reports yet — start reporting!',
    'topReporters': 'TOP REPORTERS',
    'seeAll': 'See All',
    'loading': 'Loading...',
    'loadingReports': 'Loading reports...',
    'loadingCommunityStats': 'Loading community stats...',
    'complaintLetter': 'Complaint Letter — KSPCB & BBMP',
    'copy': 'Copy',
    'share': 'Share',
    'letterCopied': 'Letter copied!',
  },
  'kn': {
    'preparingDashboard': 'ನಿಮ್ಮ ವಾಯು ಡ್ಯಾಶ್‌ಬೋರ್ಡ್ ಸಿದ್ಧವಾಗುತ್ತಿದೆ...',
    'loadingInsights': 'ಬೆಂಗಳೂರು ವಾಯು ಮಾಹಿತಿಯನ್ನು ಲೋಡ್ ಮಾಡಲಾಗುತ್ತಿದೆ...',
    'readyToExplore': 'ನಗರದ ವಾಯುವನ್ನು ನೋಡಲು ಸಿದ್ಧವಾಗಿದೆ.',
    'appSubtitleNative': 'ವಾಯು ನೇತ್ರ',
    'appTagline': '"ಬೆಂಗಳೂರು ಗಾಳಿಯ ಕಣ್ಣು"',
    'welcomeBack': 'ಮತ್ತೆ ಸ್ವಾಗತ',
    'loginToReport': 'ಮಾಲಿನ್ಯ ವರದಿ ಮಾಡಲು ಲಾಗಿನ್ ಮಾಡಿ',
    'emailAddress': 'ಇಮೇಲ್ ವಿಳಾಸ',
    'password': 'ಪಾಸ್‌ವರ್ಡ್',
    'login': 'ಲಾಗಿನ್',
    'newHere': 'ಹೊಸ ಬಳಕೆದಾರರಾ?',
    'register': 'ನೋಂದಣಿ',
    'createAccount': 'ಖಾತೆ ಸೃಷ್ಟಿಸಿ',
    'joinCommunity': 'ಬೆಂಗಳೂರು ವಾಯು ಗುಣಮಟ್ಟ ಸಮುದಾಯಕ್ಕೆ ಸೇರಿ',
    'fullName': 'ಪೂರ್ಣ ಹೆಸರು',
    'passwordMin': 'ಪಾಸ್‌ವರ್ಡ್ (ಕನಿಷ್ಠ 8 ಅಕ್ಷರಗಳು)',
    'confirmPassword': 'ಪಾಸ್‌ವರ್ಡ್ ದೃಢೀಕರಿಸಿ',
    'strongPassword': 'ಬಲವಾದ ಪಾಸ್‌ವರ್ಡ್',
    'useEightChars': '8+ ಅಕ್ಷರಗಳನ್ನು ಬಳಸಿ',
    'passwordsDoNotMatch': 'ಪಾಸ್‌ವರ್ಡ್‌ಗಳು ಹೊಂದಿಕೆಯಾಗುತ್ತಿಲ್ಲ',
    'livePollutionMap': 'ನೇರ ಮಾಲಿನ್ಯ ನಕ್ಷೆ',
    'reports': 'ವರದಿಗಳು',
    'report': 'ವರದಿ',
    'viewFullReport': 'ಪೂರ್ಣ ವರದಿ ನೋಡಿ',
    'reportPollution': 'ಮಾಲಿನ್ಯ ವರದಿ',
    'tapToTakePhoto': 'ಫೋಟೋ ತೆಗೆಯಲು ಟ್ಯಾಪ್ ಮಾಡಿ',
    'orUseButtons': 'ಅಥವಾ ಕೆಳಗಿನ ಬಟನ್‌ಗಳನ್ನು ಬಳಸಿ',
    'camera': 'ಕ್ಯಾಮೆರಾ',
    'gallery': 'ಗ್ಯಾಲರಿ',
    'nextAddDetails': 'ಮುಂದೆ: ವಿವರಗಳನ್ನು ಸೇರಿಸಿ',
    'areaHint': 'ಪ್ರದೇಶ (ಉದಾ. ಕೋರಮಂಗಲ, ವೈಟ್‌ಫೀಲ್ಡ್)',
    'useMyGpsLocation': 'ನನ್ನ GPS ಸ್ಥಳ ಬಳಸಿ',
    'detecting': 'ಗುರುತಿಸಲಾಗುತ್ತಿದೆ...',
    'descriptionHint': 'ಮಾಲಿನ್ಯವನ್ನು ವಿವರಿಸಿ (ಐಚ್ಛಿಕ — ನೋವಾ AI ಫೋಟೋ ವಿಶ್ಲೇಷಿಸುತ್ತದೆ)',
    'novaDescription': 'ಅಮೆಜಾನ್ ನೋವಾ 2 ಲೈಟ್ ನಿಮ್ಮ ಫೋಟೋವನ್ನು ವಿಶ್ಲೇಷಿಸಿ KSPCB ದೂರು ಪತ್ರವನ್ನು ಸ್ವಯಂಚಾಲಿತವಾಗಿ ಸೃಷ್ಟಿಸುತ್ತದೆ',
    'back': 'ಹಿಂದೆ',
    'analyze': 'ವಿಶ್ಲೇಷಿಸಿ',
    'novaAnalyzing': 'ನೋವಾ 2 ಲೈಟ್ ವಿಶ್ಲೇಷಿಸುತ್ತಿದೆ...',
    'uploadingPhoto': 'ಫೋಟೋ ಅಪ್‌ಲೋಡ್ ಮಾಡಲಾಗುತ್ತಿದೆ...',
    'analyzingPollution': 'ನೋವಾ 2 ಲೈಟ್ ಮಾಲಿನ್ಯವನ್ನು ವಿಶ್ಲೇಷಿಸುತ್ತಿದೆ...',
    'generatingComplaint': 'ದೂರು ಪತ್ರ ಸೃಷ್ಟಿಸಲಾಗುತ್ತಿದೆ...',
    'healthRisk': 'ಆರೋಗ್ಯ ಅಪಾಯ',
    'confidence': 'ವಿಶ್ವಾಸ ಮಟ್ಟ',
    'recommendations': 'ಶಿಫಾರಸುಗಳು',
    'myReports': 'ನನ್ನ ವರದಿಗಳು',
    'reportAgain': 'ಮತ್ತೆ ವರದಿ ಮಾಡಿ',
    'loginToSubmit': 'ಸಲ್ಲಿಸಲು ಲಾಗಿನ್ ಮಾಡಿ',
    'photoSavedLogin': 'ನಿಮ್ಮ ಫೋಟೋ ಉಳಿಸಲಾಗಿದೆ. ಸಲ್ಲಿಸಲು ಲಾಗಿನ್ ಮಾಡಿ.',
    'loginSubmit': 'ಲಾಗಿನ್ ಮಾಡಿ ಸಲ್ಲಿಸಿ',
    'aiAgent': 'AI ಸಹಾಯಕ',
    'poweredByNova': 'ಅಮೆಜಾನ್ ನೋವಾ 2 ಲೈಟ್ ಚಾಲಿತ',
    'askAirQuality': 'ಬೆಂಗಳೂರು ಗಾಳಿಯ ಗುಣಮಟ್ಟದ ಬಗ್ಗೆ ಕೇಳಿ',
    'askAboutAir': 'ಗಾಳಿಯ ಬಗ್ಗೆ ಕೇಳಿ...',
    'cleanAirAreasToday': 'ಇಂದು ಬೆಂಗಳೂರಿನ ಸ್ವಚ್ಛ ಗಾಳಿ ಪ್ರದೇಶಗಳು',
    'worstPollutionAreas': 'ಈ ವಾರದ ಅತ್ಯಂತ ಕೆಟ್ಟ ಮಾಲಿನ್ಯ ಪ್ರದೇಶಗಳು',
    'safeForJogging': 'ಕೋರಮಂಗಲ ಜಾಗಿಂಗ್‌ಗೆ ಸುರಕ್ಷಿತವೇ?',
    'showStats': 'ಬೆಂಗಳೂರು ಮಾಲಿನ್ಯ ಅಂಕಿಅಂಶಗಳನ್ನು ತೋರಿಸಿ',
    'howToComplaint': 'KSPCB ದೂರು ಹೇಗೆ ಸಲ್ಲಿಸಬೇಕು?',
    'findCleanAir': 'ಸ್ವಚ್ಛ ಗಾಳಿ ಹುಡುಕಿ',
    'aqiScale': 'AQI ಪ್ರಮಾಣ',
    'directions': 'ದಿಕ್ಕುಗಳು',
    'statistics': 'ಅಂಕಿಅಂಶಗಳು',
    'personal': 'ವೈಯಕ್ತಿಕ',
    'community': 'ಸಮುದಾಯ',
    'yourImpact': 'ನಿಮ್ಮ ಪರಿಣಾಮ',
    'severityBreakdown': 'ತೀವ್ರತೆ ವಿಭಾಗ',
    'bengaluruCommunity': 'ಬೆಂಗಳೂರು ಸಮುದಾಯ',
    'fullLeaderboard': 'ಪೂರ್ಣ ಲೀಡರ್ಬೋರ್ಡ್',
    'total': 'ಒಟ್ಟು',
    'today': 'ಇಂದು',
    'areas': 'ಪ್ರದೇಶಗಳು',
    'critical': 'ಗಂಭೀರ',
    'points': 'ಪಾಯಿಂಟ್‌ಗಳು',
    'profile': 'ಪ್ರೊಫೈಲ್',
    'memberSince': 'ಸದಸ್ಯರಾದ ವರ್ಷ',
    'badges': 'ಬ್ಯಾಡ್ಜ್‌ಗಳು',
    'language': 'ಭಾಷೆ',
    'english': 'ಇಂಗ್ಲಿಷ್',
    'kannada': 'ಕನ್ನಡ',
    'hindi': 'ಹಿಂದಿ',
    'shareApp': 'ಆಪ್ ಹಂಚಿಕೆ',
    'logout': 'ಲಾಗ್ ಔಟ್',
    'notLoggedIn': 'ಲಾಗಿನ್ ಆಗಿಲ್ಲ',
    'quickActions': 'ಶೀಘ್ರ ಕ್ರಿಯೆಗಳು',
    'reportPollutionAction': 'ಮಾಲಿನ್ಯ ವರದಿ',
    'liveMap': 'ನೇರ ನಕ್ಷೆ',
    'cleanAir': 'ಸ್ವಚ್ಛ ಗಾಳಿ',
    'todayInBengaluru': 'ಇಂದು ಬೆಂಗಳೂರಿನಲ್ಲಿ',
    'myRecentReports': 'ನನ್ನ ಇತ್ತೀಚಿನ ವರದಿಗಳು',
    'viewAll': 'ಎಲ್ಲವನ್ನೂ ನೋಡಿ',
    'noReportsYet': 'ಇನ್ನೂ ವರದಿಗಳಿಲ್ಲ — ಈಗಲೇ ಪ್ರಾರಂಭಿಸಿ!',
    'topReporters': 'ಶ್ರೇಷ್ಠ ವರದಿಗಾರರು',
    'seeAll': 'ಎಲ್ಲವನ್ನೂ ನೋಡಿ',
    'loading': 'ಲೋಡ್ ಮಾಡಲಾಗುತ್ತಿದೆ...',
    'loadingReports': 'ವರದಿಗಳನ್ನು ಲೋಡ್ ಮಾಡಲಾಗುತ್ತಿದೆ...',
    'loadingCommunityStats': 'ಸಮುದಾಯ ಅಂಕಿಅಂಶಗಳನ್ನು ಲೋಡ್ ಮಾಡಲಾಗುತ್ತಿದೆ...',
    'complaintLetter': 'ದೂರು ಪತ್ರ — KSPCB & BBMP',
    'copy': 'ನಕಲಿಸಿ',
    'share': 'ಹಂಚಿಕೆ',
    'letterCopied': 'ಪತ್ರ ನಕಲಿಸಲಾಗಿದೆ!',
  },
  'hi': {
    'preparingDashboard': 'आपका एयर डैशबोर्ड तैयार किया जा रहा है...',
    'loadingInsights': 'बेंगलुरु की वायु जानकारी लोड हो रही है...',
    'readyToExplore': 'शहर की हवा देखने के लिए तैयार है।',
    'appSubtitleNative': 'वायु नेत्र',
    'appTagline': '"बेंगलुरु की हवा पर नज़र"',
    'welcomeBack': 'फिर से स्वागत है',
    'loginToReport': 'प्रदूषण रिपोर्ट करने के लिए लॉगिन करें',
    'emailAddress': 'ईमेल पता',
    'password': 'पासवर्ड',
    'login': 'लॉगिन',
    'newHere': 'नए हैं?',
    'register': 'रजिस्टर',
    'createAccount': 'खाता बनाएं',
    'joinCommunity': 'बेंगलुरु एयर क्वालिटी समुदाय से जुड़ें',
    'fullName': 'पूरा नाम',
    'passwordMin': 'पासवर्ड (कम से कम 8 अक्षर)',
    'confirmPassword': 'पासवर्ड की पुष्टि करें',
    'strongPassword': 'मज़बूत पासवर्ड',
    'useEightChars': '8+ अक्षरों का उपयोग करें',
    'passwordsDoNotMatch': 'पासवर्ड मेल नहीं खा रहे',
    'livePollutionMap': 'लाइव प्रदूषण मानचित्र',
    'reports': 'रिपोर्ट्स',
    'report': 'रिपोर्ट',
    'viewFullReport': 'पूरी रिपोर्ट देखें',
    'reportPollution': 'प्रदूषण रिपोर्ट',
    'tapToTakePhoto': 'फोटो लेने के लिए टैप करें',
    'orUseButtons': 'या नीचे दिए गए बटन उपयोग करें',
    'camera': 'कैमरा',
    'gallery': 'गैलरी',
    'nextAddDetails': 'अगला: विवरण जोड़ें',
    'areaHint': 'क्षेत्र (उदा. कोरमंगला, व्हाइटफील्ड)',
    'useMyGpsLocation': 'मेरा GPS स्थान उपयोग करें',
    'detecting': 'पता लगाया जा रहा है...',
    'descriptionHint': 'प्रदूषण का विवरण दें (वैकल्पिक — नोवा AI फोटो का विश्लेषण करेगा)',
    'novaDescription': 'Amazon Nova 2 Lite आपकी फोटो का विश्लेषण कर KSPCB शिकायत पत्र स्वतः बनाएगा',
    'back': 'वापस',
    'analyze': 'विश्लेषण करें',
    'novaAnalyzing': 'नोवा 2 लाइट विश्लेषण कर रहा है...',
    'uploadingPhoto': 'फोटो अपलोड हो रही है...',
    'analyzingPollution': 'नोवा 2 लाइट प्रदूषण का विश्लेषण कर रहा है...',
    'generatingComplaint': 'शिकायत पत्र तैयार हो रहा है...',
    'healthRisk': 'स्वास्थ्य जोखिम',
    'confidence': 'विश्वास स्तर',
    'recommendations': 'सिफारिशें',
    'myReports': 'मेरी रिपोर्ट्स',
    'reportAgain': 'फिर से रिपोर्ट करें',
    'loginToSubmit': 'जमा करने के लिए लॉगिन करें',
    'photoSavedLogin': 'आपकी फोटो सेव हो गई है। जमा करने के लिए लॉगिन करें।',
    'loginSubmit': 'लॉगिन करें और जमा करें',
    'aiAgent': 'AI एजेंट',
    'poweredByNova': 'Amazon Nova 2 Lite द्वारा संचालित',
    'askAirQuality': 'बेंगलुरु की हवा के बारे में पूछें',
    'askAboutAir': 'हवा के बारे में पूछें...',
    'cleanAirAreasToday': 'आज बेंगलुरु के स्वच्छ हवा वाले क्षेत्र',
    'worstPollutionAreas': 'इस सप्ताह के सबसे खराब प्रदूषण क्षेत्र',
    'safeForJogging': 'क्या कोरमंगला जॉगिंग के लिए सुरक्षित है?',
    'showStats': 'बेंगलुरु प्रदूषण आँकड़े दिखाएँ',
    'howToComplaint': 'KSPCB शिकायत कैसे करें?',
    'findCleanAir': 'स्वच्छ हवा खोजें',
    'aqiScale': 'AQI स्केल',
    'directions': 'दिशाएँ',
    'statistics': 'आँकड़े',
    'personal': 'व्यक्तिगत',
    'community': 'समुदाय',
    'yourImpact': 'आपका प्रभाव',
    'severityBreakdown': 'गंभीरता विभाजन',
    'bengaluruCommunity': 'बेंगलुरु समुदाय',
    'fullLeaderboard': 'पूरा लीडरबोर्ड',
    'total': 'कुल',
    'today': 'आज',
    'areas': 'क्षेत्र',
    'critical': 'गंभीर',
    'points': 'अंक',
    'profile': 'प्रोफाइल',
    'memberSince': 'सदस्यता वर्ष',
    'badges': 'बैज',
    'language': 'भाषा',
    'english': 'अंग्रेज़ी',
    'kannada': 'कन्नड़',
    'hindi': 'हिंदी',
    'shareApp': 'ऐप साझा करें',
    'logout': 'लॉगआउट',
    'notLoggedIn': 'लॉगिन नहीं किया',
    'quickActions': 'त्वरित क्रियाएँ',
    'reportPollutionAction': 'प्रदूषण रिपोर्ट करें',
    'liveMap': 'लाइव मैप',
    'cleanAir': 'स्वच्छ हवा',
    'todayInBengaluru': 'आज बेंगलुरु में',
    'myRecentReports': 'मेरी हाल की रिपोर्ट्स',
    'viewAll': 'सब देखें',
    'noReportsYet': 'अभी तक कोई रिपोर्ट नहीं — अभी शुरू करें!',
    'topReporters': 'शीर्ष रिपोर्टर',
    'seeAll': 'सब देखें',
    'loading': 'लोड हो रहा है...',
    'loadingReports': 'रिपोर्ट्स लोड हो रही हैं...',
    'loadingCommunityStats': 'समुदाय आँकड़े लोड हो रहे हैं...',
    'complaintLetter': 'शिकायत पत्र — KSPCB और BBMP',
    'copy': 'कॉपी',
    'share': 'शेयर',
    'letterCopied': 'पत्र कॉपी हो गया!',
  },
};
